export enum ActionTypes {
  CHARACTERS_LOADING = 'CHARACTERS_LOADING',
  CHARACTERS_FAILED  = 'CHARACTERS_FAILED',
  ADD_CHARACTERS = 'ADD_CHARACTERS',
  LOCATIONS_LOADING = 'LOCATIONS_LOADING',
  LOCATIONS_FAILED = 'LOCATIONS_FAILED',
  ADD_LOCATIONS = 'ADD_LOCATIONS',
  EPISODES_LOADING = 'EPISODES_LOADING',
  EPISODES_FAILED = 'EPISODES_FAILED',
  ADD_EPISODES = 'ADD_EPISODES',
}
